version: '3.8'
services:
  bs-db:
    image: postgres:14
    container_name: bs-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bs-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres